name: swimmx
description: A swimming application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.8.4+5
  google_sign_in: ^4.0.0
  firebase_core: ^0.3.4
  firebase_dynamic_links: ^0.3.0
  uuid: ^2.0.2
  avatar_glow:


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - swim3.png